### ISSUE TITLE
Provide gallery as JSON

### ISSUE THREAD

**Issue by whizzzkid** [heychirag/jekyll-google-photos#1]
Dump all the images/dimensions/name as raw json so users can create their own gallery the way they want to.

For example:
* I user jekyll to dump all my blog posts as json: https://nishantarora.in/posts.json
* I can consume that to dynamically render the posts and perform on device search: https://nishantarora.in/blog/
* I can also use tags like so: https://nishantarora.in/blog/#tag:labs

This provides a way to fetch the the gallery which can be used in whatever way the user wants.

**Comment by heychirag** [comment]
The image URLs will be available under `googlePhotos.urls` on the respective page.
