### ISSUE TITLE
Normal use case no longer works

### ISSUE THREAD

**Issue by edewit** [heychirag/jekyll-google-photos#10]
Using something like:
`{% google_photos https://photos.app.goo.gl/bhWukds8QVodFU246 800 %}`

Will output 
```
<script>googlePhotos = {};googlePhotos.urls = ["https://lh3.googleusercontent.com/w..."]</script>
```
instead of creating image tag like the older versions, it behaves the same as adding 'none'

**Comment by heychirag** [comment]
@edewit Did you use to rely on it? I decided to remove it because it didn't feel to be that useful as it was nothing special. You can simply use the above image links with a plugin of your choice. Or write one of your own. If you still insist, I can bring it back in the next release.

**Comment by edewit** [comment]
Yeah I used to use it like that already migrated now to use the new way, but in the readme it still hints to that the "old" way still works. Thanks great job @heychirag
