### ISSUE TITLE
[Error] Unknown tag

### ISSUE THREAD

**Issue by ggarciabas** [heychirag/jekyll-google-photos#2]
Hello, 
I tried to use this gem but I got this error:

`❯ bundle exec jekyll serve --trace
Configuration file: /Users/X/_config.yml
            Source: /Users/X
       Destination: /Users/X/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 3): Unknown tag 'google_photos' in /_layouts/post.html
bundler: failed to load command: jekyll (/Users/X/.rvm/gems/ruby-2.6.3/bin/jekyll)
Liquid::SyntaxError: Liquid syntax error (line 3): Unknown tag 'google_photos'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/liquid-4.0.0/lib/liquid/document.rb:23:in `unknown_tag'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/liquid-4.0.0/lib/liquid/document.rb:11:in `block in parse'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/liquid-4.0.0/lib/liquid/block_body.rb:33:in `parse'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/liquid-4.0.0/lib/liquid/template.rb:132:in `parse'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/liquid-4.0.0/lib/liquid/template.rb:116:in `parse'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:121:in `render_liquid'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:195:in `render_layout'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:158:in `place_in_layouts'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:88:in `render_document'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:62:in `run'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/site.rb:479:in `render_regenerated'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `each'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `block in render_docs'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `each_value'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `render_docs'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/site.rb:191:in `render'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/site.rb:71:in `process'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/X/.rvm/gems/ruby-2.6.3/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
  /Users/X/.rvm/gems/ruby-2.6.3/bin/jekyll:23:in `load'
  /Users/X/.rvm/gems/ruby-2.6.3/bin/jekyll:23:in `<top (required)>'`

**Comment by heychirag** [comment]
Did you install the gem correctly? And added it to `_config.yml`?

**Comment by shreyas1701** [comment]
I am getting the same error

> The page build failed for the `master` branch with the following error:
> The tag `google_photos` on line 10 in `blah blah page` is not a recognized Liquid tag

**Comment by sergiotocalini** [comment]
Same issue here... I am trying to use it on github-pages and the error is:
```
The tag google_photos on line 10 in blah blah page is not a recognized Liquid tag
```
I included on the _config.yml and also added as a folder on the _plugins :(

**Comment by heychirag** [comment]
I think this is the problem you guys are facing:

> https://stackoverflow.com/questions/54499478/my-liquid-tag-is-not-recognized-by-github-pages

I would recommend you to use Gitlab pages. It's simply better :)

**Comment by heychirag** [comment]
I think this is the problem you guys are facing:

> https://stackoverflow.com/questions/54499478/my-liquid-tag-is-not-recognized-by-github-pages

**Comment by sergiotocalini** [comment]
Hi @heychirag,
Thanks for your answer. It is not clear how you related both issues.
I mean, how should we solve the issue? I can not find an example in that link.
Thanks in advance.

**Comment by heychirag** [comment]
Hi @sergiotocalini. I am talking about this:

> Since GitHub Pages supports only a limited set of Ruby Gems (https://pages.github.com/versions/), the recommended way is to build locally and push the contents of your destination folder (./_site by default) to your remote for hosting.

If the site build fine locally, then the problem lies with Github pages as it doesn't support it. I would strongly recommend you to use Gitlab pages. In my personal opinion it's far superior.

Give me follow up if you were able to get this problem solved.
