### ISSUE TITLE
creating 2 galleries on one page

### ISSUE THREAD

**Issue by edewit** [heychirag/jekyll-google-photos#4]
When one includes 2 galleries on one page the `googlePhotos` Javascript variable gets overriden by the second gallery.

**Comment by heychirag** [comment]
Yeah it was supposed to work that way because you can always create a new merged album in Google Photos. But I will try to add this feature when I get time.

**Comment by heychirag** [comment]
Thanks for requesting this feature.

[Click here](https://github.com/heychirag/jekyll-google-photos#adding-multiple-albums) to learn adding multiple galleries.
