### ISSUE TITLE
Passing a gallery URL as a variable

### ISSUE THREAD

**Issue by bethlet** [heychirag/jekyll-google-photos#7]
Passing gallery URL as a variable into this plugin seems to be unsupported.

For example:
`{% google_photos post.gallery_url 800 %}
`

Results in an error:
```
  Liquid Exception: No such file or directory @ rb_sysopen - post.gallery_url in index.html
             Error: No such file or directory @ rb_sysopen - post.gallery_url
             Error: Run jekyll build --trace for more information.
```
Is this something that can be fixed? Or is this designed to have the gallery hardcoded? If so, how is it intended to be used within templates?

**Comment by heychirag** [comment]
That's a good feature that can be implemented. Do you think you can create a PR for this? I am hardly getting any free time from my daytime job.

**Comment by bethlet** [comment]
Yes. I can send a PR later today.
